export const blogs = [
    {
        id: 1,
        slug: 'loi-ich-cua-viec-bo-thuoc-la',
        title: 'Lợi ích của việc bỏ thuốc lá',
        excerpt: 'Tìm hiểu những thay đổi tích cực cho sức khỏe của bạn khi bạn từ bỏ thuốc lá.',
        content: `Khi bạn bỏ thuốc lá, sức khỏe của bạn bắt đầu được cải thiện gần như ngay lập tức. Trong vòng 20 phút, huyết áp và nhịp tim của bạn trở về mức bình thường. Sau 1 ngày, nguy cơ đau tim giảm rõ rệt...`,
        image: '/images/blog1.jpg',
        author: 'Nguyễn Văn An',
        date: '2024-01-01',
        category: 'Health'
    },
    {
        id: 2,
        slug: 'cach-vuot-qua-con-them-thuoc',
        title: 'Cách vượt qua cơn thèm thuốc',
        excerpt: 'Những chiến lược hiệu quả giúp bạn đối mặt với những thời điểm khó khăn nhất.',
        content: `Để vượt qua cơn thèm thuốc, bạn có thể thử uống nước, nhai kẹo cao su, đi dạo hoặc nói chuyện với một người bạn thân thiết...`,
        image: '/images/blog2.jpg',
        author: 'Trần Thị Bình',
        date: '2024-01-10',
        category: 'Tips'
    },
    {
        id: 3,
        slug: 'chia-se-thanh-cong',
        title: 'Chia sẻ từ người đã bỏ thuốc thành công',
        excerpt: 'Câu chuyện truyền cảm hứng từ những người đã làm chủ được cuộc sống không thuốc lá.',
        content: `Anh Nam từng hút thuốc 15 năm nhưng đã bỏ thuốc thành công nhờ sự động viên của gia đình và ý chí kiên định...`,
        image: '/images/blog3.jpg',
        author: 'Phạm Quang Nam',
        date: '2024-01-15',
        category: 'Story'
    },
    {
        id: 4,
        slug: 'huong-dan-bat-dau-cai-thuoc',
        title: 'Hướng dẫn bắt đầu cai thuốc lá',
        excerpt: 'Các bước cơ bản giúp bạn lên kế hoạch và bắt đầu hành trình bỏ thuốc.',
        content: `Để bắt đầu, hãy đặt ra ngày bạn sẽ bỏ thuốc. Loại bỏ thuốc lá khỏi nhà và chuẩn bị các phương án thay thế...`,
        image: '/images/blog3.jpg',
        author: 'Lê Mỹ Linh',
        date: '2024-02-01',
        category: 'Guide'
    },
    {
        id: 5,
        slug: 'xu-huong-song-khoe',
        title: 'Xu hướng sống khoẻ hiện đại',
        excerpt: 'Khám phá các xu hướng sống khoẻ được yêu thích năm 2024.',
        content: `Năm 2024 chứng kiến sự bùng nổ của các xu hướng sống xanh, tập luyện thể thao và ăn uống lành mạnh...`,
        image: '/images/blog1.jpg',
        author: 'Hoàng Minh',
        date: '2024-02-14',
        category: 'Health'
    },
    {
        id: 6,
        slug: 'mon-an-tot-cho-suc-khoe',
        title: '10 món ăn tốt cho sức khoẻ',
        excerpt: 'Danh sách các món ăn vừa ngon vừa tốt cho sức khoẻ.',
        content: `Ăn uống lành mạnh là một trong những bí quyết sống khoẻ. Dưới đây là 10 món ăn vừa ngon vừa giúp bảo vệ sức khoẻ của bạn...`,
        image: '/images/blog3.jpg',
        author: 'Lưu Quỳnh Anh',
        date: '2024-03-03',
        category: 'Food'
    },
    {
        id: 7,
        slug: 'lam-sao-de-tu-bo-thoi-quen-xau',
        title: 'Làm sao để từ bỏ thói quen xấu?',
        excerpt: 'Các bước giúp bạn thay đổi thói quen xấu một cách hiệu quả.',
        content: `Thay đổi thói quen là quá trình không dễ dàng. Tuy nhiên, với quyết tâm và sự hỗ trợ, bạn hoàn toàn có thể làm được...`,
        image: '/images/blog2.jpg',
        author: 'Vũ Trung',
        date: '2024-03-12',
        category: 'Tips'
    },
    {
        id: 8,
        slug: 'top-5-sach-truyen-cam-hung',
        title: 'Top 5 cuốn sách truyền cảm hứng',
        excerpt: 'Những cuốn sách giúp bạn có thêm động lực sống tích cực.',
        content: `Sách là nguồn cảm hứng bất tận. Dưới đây là 5 cuốn sách truyền động lực rất được yêu thích năm nay...`,
        image: '/images/blog1.jpg',
        author: 'Ngô Bảo',
        date: '2024-03-18',
        category: 'Book'
    },
    {
        id: 9,
        slug: 'bo-thuoc-la-truoc-tuoi-30',
        title: 'Bỏ thuốc lá trước tuổi 30',
        excerpt: 'Vì sao nên bỏ thuốc lá càng sớm càng tốt?',
        content: `Các nghiên cứu chỉ ra rằng, bỏ thuốc lá trước tuổi 30 giúp giảm đáng kể nguy cơ bệnh tật và tăng tuổi thọ...`,
        image: '/images/blog3.jpg',
        author: 'Trịnh Hương',
        date: '2024-03-25',
        category: 'Health'
    },
    {
        id: 10,
        slug: 'giu-vung-quyet-tam',
        title: 'Giữ vững quyết tâm trong hành trình cai thuốc',
        excerpt: 'Bí quyết giữ lửa ý chí trên con đường bỏ thuốc lá.',
        content: `Những người thành công trong việc bỏ thuốc đều có chung một điểm: quyết tâm và không từ bỏ dù gặp khó khăn...`,
        image: '/images/blog2.jpg',
        author: 'Đỗ Thái Sơn',
        date: '2024-04-02',
        category: 'Story'
    },
    {
        id: 11,
        slug: '5-ly-do-nen-tap-the-duc',
        title: '5 lý do nên tập thể dục mỗi ngày',
        excerpt: 'Vận động thể chất mang lại những lợi ích không ngờ.',
        content: `Tập thể dục không chỉ giúp bạn khoẻ mạnh mà còn cải thiện tinh thần, giúp làm việc hiệu quả hơn...`,
        image: '/images/blog1.jpg',
        author: 'Phan Hữu Hùng',
        date: '2024-04-11',
        category: 'Health'
    },
    {
        id: 12,
        slug: 'lam-sao-de-khong-tai-nghien',
        title: 'Làm sao để không tái nghiện?',
        excerpt: 'Chia sẻ kinh nghiệm tránh tái nghiện hiệu quả.',
        content: `Việc tránh tái nghiện đòi hỏi sự cảnh giác và xây dựng môi trường sống tích cực...`,
        image: '/images/blog3.jpg',
        author: 'Phạm Tuấn',
        date: '2024-04-21',
        category: 'Guide'
    },
    {
        id: 13,
        slug: 'phuong-phap-thu-gian-dau-oc',
        title: 'Phương pháp thư giãn đầu óc nhanh chóng',
        excerpt: 'Các mẹo giúp giải tỏa căng thẳng ngay lập tức.',
        content: `Thiền, nghe nhạc nhẹ và vận động nhẹ là những cách thư giãn đầu óc hiệu quả...`,
        image: '/images/blog2.jpg',
        author: 'Lê Cẩm Linh',
        date: '2024-04-30',
        category: 'Tips'
    },
    {
        id: 14,
        slug: 'ban-co-can-chuyen-gia-tu-van',
        title: 'Bạn có cần chuyên gia tư vấn không?',
        excerpt: 'Khi nào nên tìm đến chuyên gia tâm lý?',
        content: `Nếu cảm thấy khó khăn kéo dài, hãy tìm đến chuyên gia tư vấn để được hỗ trợ đúng cách...`,
        image: '/images/blog1.jpg',
        author: 'Nguyễn Hải Đăng',
        date: '2024-05-08',
        category: 'Story'
    },
    {
        id: 15,
        slug: '10-thoi-quen-tot-moi-ngay',
        title: '10 thói quen tốt mỗi ngày cho sức khoẻ',
        excerpt: 'Thực hiện những thói quen nhỏ mang lại thay đổi lớn.',
        content: `Dậy sớm, uống đủ nước, tập thể dục và suy nghĩ tích cực là những thói quen rất tốt cho sức khoẻ...`,
        image: '/images/blog3.jpg',
        author: 'Hồ Thị Thanh',
        date: '2024-05-18',
        category: 'Health'
    },
    {
        id: 16,
        slug: 'ky-nang-song',
        title: 'Kỹ năng sống cần thiết thời đại mới',
        excerpt: 'Những kỹ năng nào giúp bạn thành công trong cuộc sống hiện đại?',
        content: `Giao tiếp, quản lý thời gian, và học hỏi liên tục là các kỹ năng quan trọng của thế kỷ 21...`,
        image: '/images/blog2.jpg',
        author: 'Mai Quốc Việt',
        date: '2024-05-22',
        category: 'Skill'
    },
    {
        id: 17,
        slug: 'thay-doi-ban-than',
        title: 'Thay đổi bản thân từ những điều nhỏ nhất',
        excerpt: 'Thành công bắt đầu từ việc thay đổi thói quen mỗi ngày.',
        content: `Hãy bắt đầu thay đổi từ những việc nhỏ nhất để xây dựng nền tảng cho sự phát triển lớn hơn...`,
        image: '/images/blog1.jpg',
        author: 'Lưu Thanh Tùng',
        date: '2024-06-01',
        category: 'Tips'
    },
    {
        id: 18,
        slug: 'nhung-loi-khuyen-cua-chuyen-gia',
        title: 'Những lời khuyên của chuyên gia về cai thuốc',
        excerpt: 'Lời khuyên thực tế từ các chuyên gia đầu ngành.',
        content: `Các chuyên gia khuyên nên xây dựng lối sống lành mạnh và tham gia các nhóm hỗ trợ để bỏ thuốc thành công...`,
        image: '/images/blog3.jpg',
        author: 'Võ Ngọc Phúc',
        date: '2024-06-09',
        category: 'Guide'
    },
    {
        id: 19,
        slug: 'kham-pha-nhung-dieu-moi',
        title: 'Khám phá những điều mới mỗi ngày',
        excerpt: 'Làm thế nào để duy trì sự hứng khởi trong cuộc sống?',
        content: `Thử thách bản thân, học kỹ năng mới và du lịch giúp cuộc sống luôn thú vị...`,
        image: '/images/blog2.jpg',
        author: 'Tạ Đình Phúc',
        date: '2024-06-14',
        category: 'Skill'
    },
    {
        id: 20,
        slug: 'cai-thuoc-thanh-cong-la-nhu-the-nao',
        title: 'Cai thuốc thành công là như thế nào?',
        excerpt: 'Các dấu hiệu cho thấy bạn đã cai thuốc thành công.',
        content: `Cai thuốc thành công không chỉ là không hút thuốc, mà còn là xây dựng lối sống tích cực và kiểm soát cảm xúc tốt...`,
        image: '/images/blog1.jpg',
        author: 'Đinh Văn Lực',
        date: '2024-06-22',
        category: 'Story'
    }
];
