import type { Metadata } from 'next';
import './globals.css';
import { Montserrat } from 'next/font/google';
import ClientLayout from '@/app/ClientLayout';
import ApolloClientProvider from '@/apollo/apolloProviders';
import ReduxProvider from '@/components/providers/ReduxProvider';
import ScrollToTop from '@/components/common/ScrollToTop';
import ProgressBar from '@/components/common/ProgressBar';
import ToasterClient from '@/components/common/CustomToast';

const mont = Montserrat({
  subsets: ['latin', 'latin-ext'],
  weight: ['400', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'ReAir',
  description: 'Generated by create next app',
  icons: {
    icon: '/images/logo.png'
  }
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const { locale } = await params;

  return (
    <html lang={locale}>
      <body className={mont.className}>
        <ToasterClient />
        <ApolloClientProvider>
          <ReduxProvider>
              <ClientLayout>
                {children}
                <ScrollToTop />
                <ProgressBar />
              </ClientLayout>
          </ReduxProvider>
        </ApolloClientProvider>
      </body>
    </html>
  );
}
