import { NextIntlClientProvider } from 'next-intl';
import { notFound } from 'next/navigation';
import { Locale, routing } from '@/i18n/routing';
import type { Metadata } from 'next';
import './globals.css';
import { getMessages } from 'next-intl/server';
import { Montserrat } from 'next/font/google';
import ClientLayout from '../ClientLayout';
import ApolloClientProvider from '../../apollo/apolloProviders';
import ReduxProvider from '../ReduxProvider';

const mont = Montserrat({
  subsets: ['latin', 'latin-ext'],
  weight: ['400', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'ReAir',
  description: 'Generated by create next app',
  icons: {
    icon: '/images/logo.png'
  }
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const { locale } = params;

  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={mont.className}>
        <ApolloClientProvider>
          <ReduxProvider>
            <NextIntlClientProvider messages={messages}>
              <ClientLayout>
                {children}
              </ClientLayout>
            </NextIntlClientProvider>
          </ReduxProvider>
        </ApolloClientProvider>
      </body>
    </html>
  );
}
